# Generated by Django 4.1.5 on 2023-01-18 07:19

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='raw/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='list',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
