# Generated by Django 4.1.5 on 2023-01-18 08:16

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_file_alter_item_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='due_date',
            field=models.DateTimeField(default=items.models.tomorrow),
        ),
    ]
